steps:
  # Passo 1: Construir a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-app:latest', '.']

  # Passo 2: Fazer o push da imagem para o Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-app:latest']

  # Passo 3: Fazer o deploy na VM usando SSH
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-20250822-194908' # Substitua pelo nome da sua VM
      - '--zone'
      - 'us-central1-c' # Substitua pela zona da sua VM
      - '--command'
      - |
        'docker pull gcr.io/$PROJECT_ID/my-app:latest && \
         docker stop my-app || true && \
         docker rm my-app || true && \
         docker run -d --name my-app -p 80:8080 gcr.io/$PROJECT_ID/my-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY # Configuração para usar apenas o Cloud Logging

timeout: '1200s'
